name: Lint

on:
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install 

      - name: Run ESLint
        run: pnpm run lint:eslint
        continue-on-error: false

      - name: Run Stylelint
        run: pnpm run lint:stylelint
        continue-on-error: false

      - name: Check for lint errors
        if: ${{ failure() }}
        run: |
          echo "Linting failed! Please fix the errors above and try again."
          exit 1