name: Lint Code

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set your desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run ESLint
      - name: Run ESLint
        run: pnpm run lint:eslint

      # Run Stylelint
      - name: Run Stylelint
        run: pnpm run lint:stylelint

      # Optionally, you can fail the build if linting fails
      - name: Check for lint errors
        run: |
          if [[ $(pnpm run lint:eslint) != 0 || $(pnpm run lint:stylelint) != 0 ]]; then
            echo "Linting failed!"
            exit 1
          fi

