name: Lint Action

on:
  pull_request:
    branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Echo the js/ts changed files
        id: changed
        run: |
          a=""
          IFS=$'\n'
          all_changed_files='"'"${{ steps.changed-files.outputs.all_changed_files }}"'"'
          cleaned_paths=$(echo $all_changed_files | tr -d '()')
          for file in $cleaned_paths; do
            if [[ $file == *.js || $file == *.jsx || $file == *.ts || $file == *.tsx ]]; then
            a="${a} ${file}"
            fi
          done
          echo "changed_file=$a" >> $GITHUB_OUTPUT

      - name: Echo the css changed files
        id: css-changed
        run: |
          b=""
          IFS=$'\n'
          all_changed_files='"'"${{ steps.changed-files.outputs.all_changed_files }}"'"'
          cleaned_paths=$(echo $all_changed_files | tr -d '()')
          for file in $cleaned_paths; do
            if [[ $file == *.css ]]; then
            b="${b} ${file}"
            fi
          done
          echo "changed_css_file=$b" >> $GITHUB_OUTPUT

      - name: Check for eslint-disable comments
        run: |
          base_branch=${{ github.base_ref }}
          changed_files=$(git diff --name-only $base_branch HEAD)

          if [ -z "$changed_files" ]; then
            echo "No changed files."
            exit 0
          fi

          exit_code=0

          for file in $changed_files; do
            if [ -f "$file" ] && grep -q -E '(/\* eslint-disable-next-line no-restricted-imports \*/|/\* eslint-disable no-restricted-imports \*/|/\* eslint-disable \*/)' "$file"; then
              echo "Found eslint-disable or eslint-disable-next-line comments in $file."
              exit_code=1
            fi
          done

          if [ $exit_code -eq 0 ]; then
            echo "No eslint-disable or eslint-disable-next-line comments found in changed files."
          fi

          exit $exit_code

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - if: steps.changed.outputs.changed_file != ''
        name: Run ESLint
        run: pnpm eslint ${{ steps.changed.outputs.changed_file }}

      - if: steps.css-changed.outputs.changed_css_file != ''
        name: Run Stylelint
        run: pnpm stylelint ${{ steps.css-changed.outputs.changed_css_file }}