name: Lint on Pull Request

on:
  pull_request:
    branches: [main] # or any other branches you want to lint on

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: pnpm install

      - name: Check out PR changes
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}:pr
          git checkout pr

      - name: Determine changed files
        id: changed_files
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only origin/main...pr)"

      - name: Run ESLint
        run: |
          pnpm exec eslint --fix "$(steps.changed_files.outputs.changed_files)" --ext .js,.jsx,.ts,.tsx --ignore-pattern "node_modules/**"
          pnpm exec eslint "$(steps.changed_files.outputs.changed_files)" --ext .js,.jsx,.ts,.tsx --ignore-pattern "node_modules/**" 

      - name: Run Stylelint
        run: |
          pnpm exec stylelint "$(steps.changed_files.outputs.changed_files)" --fix
          pnpm exec stylelint "$(steps.changed_files.outputs.changed_files)"