name: Lint Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.js
            **/*.jsx
            **/*.ts
            **/*.tsx
            **/*.css
            **/*.scss
            **/*.sass

      - name: Run ESLint on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ESLINT_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -E '\.((j|t)sx?|vue)$' || true)
          if [ ! -z "$ESLINT_FILES" ]; then
            echo "Running ESLint on changed files:"
            echo "$ESLINT_FILES"
            pnpm eslint $ESLINT_FILES --max-warnings=0
          else
            echo "No JavaScript/TypeScript files changed"
          fi

      - name: Run StyleLint on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          STYLE_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -E '\.(css|scss|sass)$' | tr '\n' ' ' || true)
          if [ ! -z "$STYLE_FILES" ]; then
            echo "Running StyleLint on changed files:"
            echo "$STYLE_FILES"
            pnpm stylelint $STYLE_FILES
          else
            echo "No style files changed"
          fi