name: Lint Code

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparing changes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
            **/*.css
            **/*.scss
            **/*.sass

      - name: Run ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Convert newline-separated files to space-separated and filter JS/TS files
          CHANGED_JS_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr '\n' ' ' | xargs -n1 | grep -E "\.(js|jsx|ts|tsx)$" | tr '\n' ' ' || true)
          if [ ! -z "$CHANGED_JS_FILES" ]; then
            echo "Linting JavaScript/TypeScript files:"
            echo "$CHANGED_JS_FILES"
            pnpm eslint $CHANGED_JS_FILES --max-warnings=0
          else
            echo "No JavaScript/TypeScript files to lint"
          fi

      - name: Run Stylelint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Convert newline-separated files to space-separated and filter style files
          CHANGED_STYLE_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr '\n' ' ' | xargs -n1 | grep -E "\.(css|scss|sass)$" | tr '\n' ' ' || true)
          if [ ! -z "$CHANGED_STYLE_FILES" ]; then
            echo "Linting style files:"
            echo "$CHANGED_STYLE_FILES"
            pnpm stylelint $CHANGED_STYLE_FILES --max-warnings=0
          else
            echo "No style files to lint"
          fi