name: Lint Code

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.sass'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run ESLint
      - name: Run ESLint
        run: |
          pnpm run lint:eslint
          ESLINT_EXIT_CODE=$?

      # Run Stylelint
      - name: Run Stylelint
        run: |
          pnpm run lint:stylelint
          STYLELINT_EXIT_CODE=$?

      # Check for lint errors
      - name: Check for lint errors
        run: |
          if [[ $ESLINT_EXIT_CODE != 0 || $STYLELINT_EXIT_CODE != 0 ]]; then
            echo "Linting failed!"
            exit 1
          fi
